apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: auto-event-generator
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-event-generator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auto-event-generator
    spec:
      serviceAccountName: wso2svcacct
      imagePullSecrets:
        - name: dockercred
      containers:
      - name: auto-event-generator
        image: 557350676069.dkr.ecr.us-east-1.amazonaws.com/plt-realtime/plt-realtime-event-generator:1.0.17
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_SERVERS
          value: "kafka-service.wso2:9092"
        - name: KAFKA_TOPIC
          value: siddhi-test
        - name: AUTO_GENERATE_EVENT
          value: "true"
        - name: EVENT_INTERVAL
          value: "-1"
---
apiVersion: v1
kind: Service
metadata:
  name: auto-event-generator-svc
  namespace: wso2
spec:
  selector:
    app: auto-event-generator
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080        
---