apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: event-generator
  namespace: wso2
spec:
  replicas: $COUNT
  selector:
    matchLabels:
      app: event-generator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: event-generator
    spec:
      serviceAccountName: wso2svcacct
      imagePullSecrets:
        - name: dockercred
      containers:
      - name: event-generator
        image: 557350676069.dkr.ecr.us-east-1.amazonaws.com/plt-realtime/plt-realtime-event-generator:1.0.$BUILD_ID
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_SERVERS
          value: "kafka-service.wso2:9092"
        - name: KAFKA_TOPIC
          value: siddhi-test
        - name: AUTO_GENERATE_EVENT
          value: "false"
        - name: EVENT_INTERVAL
          value: "-1"
---
apiVersion: v1
kind: Service
metadata:
  name: event-generator-svc
  namespace: wso2
spec:
  selector:
    app: event-generator
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080        
---